// High-fidelity Mock Database for Philippines iHubs Directory
// This is used as a fallback if Google Sheets cannot be reached, ensuring 100% offline availability.

const mockRegions = [
  {
    region_iso: "PH-00",
    region_name: "National Capital Region (NCR)",
    focal_person: "Mr. Osric Primo Bern Quibot",
    position: "Regional Director, DOST NCR",
    contact_number: "0286837790",
    email: "osric.quibot@ncr.dost.gov.ph"
  },
  {
    region_iso: "PH-01",
    region_name: "Ilocos (Region I)",
    focal_person: "Engr. Teresita A. Tabaog",
    position: "Regional Director, DOST I",
    contact_number: "0920-555-5678",
    email: "t.tabaog@region1.dost.gov.ph"
  },
  {
    region_iso: "PH-02",
    region_name: "Cagayan Valley (Region II)",
    focal_person: "Virginia G. Bilgera",
    position: "Regional Director, DOST II",
    contact_number: "0998-123-4567",
    email: "v.bilgera@region2.dost.gov.ph"
  },
  {
    region_iso: "PH-03",
    region_name: "Central Luzon (Region III)",
    focal_person: "Dr. Julius Caesar V. Sicat",
    position: "Regional Director, DOST III",
    contact_number: "0919-876-5432",
    email: "jc.sicat@region3.dost.gov.ph"
  },
  {
    region_iso: "PH-40",
    region_name: "CALABARZON (Region IV-A)",
    focal_person: "Emelita P. Bagsit",
    position: "Regional Director, DOST IV-A",
    contact_number: "0918-321-7654",
    email: "e.bagsit@calabarzon.dost.gov.ph"
  },
  {
    region_iso: "PH-41",
    region_name: "MIMAROPA (Region IV-B)",
    focal_person: "Dr. Ma. Josefina P. Abilay",
    position: "Regional Director, DOST MIMAROPA",
    contact_number: "0917-456-7890",
    email: "mj.abilay@mimaropa.dost.gov.ph"
  },
  {
    region_iso: "PH-05",
    region_name: "Bicol (Region V)",
    focal_person: "Rommel R. Serrano",
    position: "Regional Director, DOST V",
    contact_number: "0995-987-6543",
    email: "r.serrano@region5.dost.gov.ph"
  },
  {
    region_iso: "PH-06",
    region_name: "Western Visayas (Region VI)",
    focal_person: "Maerell Love C. Senalista, RPm",
    position: "Innovation Management Unit Head",
    contact_number: "09770142783",
    email: "maerelllove.senalista@ro6.dost.gov.ph"
  },
  {
    region_iso: "PH-07",
    region_name: "Central Visayas (Region VII)",
    focal_person: "Engr. Jesus F. Zamora Jr.",
    position: "Regional Director, DOST VII",
    contact_number: "0917-345-6789",
    email: "j.zamora@region7.dost.gov.ph"
  },
  {
    region_iso: "PH-08",
    region_name: "Eastern Visayas (Region VIII)",
    focal_person: "Engr. Ernesto M. Granada",
    position: "Regional Director, DOST VIII",
    contact_number: "0920-765-4321",
    email: "e.granada@region8.dost.gov.ph"
  },
  {
    region_iso: "PH-09",
    region_name: "Zamboanga Peninsula (Region IX)",
    focal_person: "Martin A. Wee",
    position: "Regional Director, DOST IX",
    contact_number: "0998-654-3210",
    email: "m.wee@region9.dost.gov.ph"
  },
  {
    region_iso: "PH-10",
    region_name: "Northern Mindanao (Region X)",
    focal_person: "Engr. Romela N. Ratilla",
    position: "Regional Director, DOST X",
    contact_number: "0917-987-1234",
    email: "r.ratilla@region10.dost.gov.ph"
  },
  {
    region_iso: "PH-11",
    region_name: "Davao (Region XI)",
    focal_person: "Dr. Anthony C. Sales, CESO III",
    position: "Regional Director, DOST XI",
    contact_number: "0920-111-2222",
    email: "a.sales@region11.dost.gov.ph"
  },
  {
    region_iso: "PH-12",
    region_name: "SOCCSKSARGEN (Region XII)",
    focal_person: "Gisela M. Lunasco",
    position: "Regional Focal Person",
    contact_number: "0919-333-4444",
    email: "g.lunasco@region12.dost.gov.ph"
  },
  {
    region_iso: "PH-13",
    region_name: "Caraga (Region XIII)",
    focal_person: "Engr. Noel M. Ajoc",
    position: "Regional Director, DOST Caraga",
    contact_number: "0918-555-6666",
    email: "n.ajoc@caraga.dost.gov.ph"
  },
  {
    region_iso: "PH-14",
    region_name: "BARMM",
    focal_person: "Minister Engr. Aida Silongan",
    position: "MOST BARMM Minister",
    contact_number: "0906-777-8888",
    email: "a.silongan@most.bangsamoro.gov.ph"
  },
  {
    region_iso: "PH-15",
    region_name: "CAR",
    focal_person: "Dr. Nancy A. Bantog",
    position: "Regional Director, DOST CAR",
    contact_number: "0917-222-3333",
    email: "n.bantog@car.dost.gov.ph"
  }
];

// 78 Mock iHub locations matching the statistics in the layout.
// Region VI contains the 4 shown in the mockup + 1 additional for Bacolod.
const mockIHubs = [
  // --- REGION 6: WESTERN VISAYAS (5 iHubs: 1 Regional, 4 Provincial) ---
  {
    id: "ihub-r6-01",
    name: "WV iHub",
    type: "Regional iHub",
    institution: "Iloilo Science and Technology University",
    province: "Iloilo",
    province_iso: "PH-ILI",
    region_iso: "PH-06",
    address: "5F Research Hub, ISAT U Main Campus, La Paz, Iloilo City",
    focal_person: "Dr. Carmelo V. Ambut",
    contact_number: "0917-765-4321",
    email: "c.ambut@isatu.edu.ph",
    latitude: 10.7161,
    longitude: 122.5694,
    image_url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r6-02",
    name: "Aklan iHub",
    type: "Provincial iHub",
    institution: "DOST - Aklan PSTO",
    province: "Aklan",
    province_iso: "PH-AKL",
    region_iso: "PH-06",
    address: "Provincial Capital Compound, Kalibo, Aklan",
    focal_person: "Engr. Aron Q. Garcia",
    contact_number: "0939-123-4567",
    email: "a.garcia@ro6.dost.gov.ph",
    latitude: 11.7058,
    longitude: 122.3619,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r6-03",
    name: "Antique iHub",
    type: "Provincial iHub",
    institution: "DOST-Antique",
    province: "Antique",
    province_iso: "PH-ANT",
    region_iso: "PH-06",
    address: "Gate 3, UA-Sibalom Campus, Mayor Santiago Lotilla St., Sibalom, Antique",
    focal_person: "Felia Margarejo",
    contact_number: "0920-987-6543",
    email: "f.margarejo@ro6.dost.gov.ph",
    latitude: 10.8286,
    longitude: 122.0125,
    image_url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r6-04",
    name: "Capiz iHub",
    type: "Provincial iHub",
    institution: "DOST - Capiz",
    province: "Capiz",
    province_iso: "PH-CAP",
    region_iso: "PH-06",
    address: "Fuentes Drive, Roxas City",
    focal_person: "Gerardo M. Jimenez",
    contact_number: "0917-823-1122",
    email: "g.jimenez@ro6.dost.gov.ph",
    latitude: 11.5761,
    longitude: 122.7569,
    image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r6-05",
    name: "Guimaras iHub",
    type: "Provincial iHub",
    institution: "Guimaras State University - Main Campus",
    province: "Guimaras",
    province_iso: "PH-GUI",
    region_iso: "PH-06",
    address: "GSU Main Campus, Buenavista, Guimaras",
    focal_person: "Engr. Eric R. Valenzuela",
    contact_number: "0998-345-6789",
    email: "e.valenzuela@gsu.edu.ph",
    latitude: 10.6657,
    longitude: 122.6288,
    image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r6-06",
    name: "Bacolod iHub",
    type: "Provincial iHub",
    institution: "Negros Occidental Provincial PSTO",
    province: "Negros Occidental",
    province_iso: "PH-NEC",
    region_iso: "PH-06",
    address: "Cottage Road, Bacolod City",
    focal_person: "Glenda L. Rillo",
    contact_number: "0919-654-9876",
    email: "g.rillo@ro6.dost.gov.ph",
    latitude: 10.6765,
    longitude: 122.9509,
    image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // --- NCR: NATIONAL CAPITAL REGION (10 iHubs: 3 Regional, 7 Provincial) ---
  {
    id: "ihub-ncr-01",
    name: "NCR Innovation Hub (QC)",
    type: "Regional iHub",
    institution: "DOST NCR Regional Office",
    province: "Quezon City",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "DOST-NCR Bldg., Bicutan, Taguig City (Main Office) / QC Branch",
    focal_person: "Warren Alano",
    contact_number: "0917-111-2222",
    email: "w.alano@ncr.dost.gov.ph",
    latitude: 14.6760,
    longitude: 121.0437,
    image_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-02",
    name: "Ateneo Innovation Center",
    type: "Regional iHub",
    institution: "Ateneo de Manila University",
    province: "Quezon City",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "Katipunan Ave, Loyola Heights, Quezon City",
    focal_person: "Dr. Gregory L. Tangonan",
    contact_number: "0920-333-4444",
    email: "gtangonan@ateneo.edu",
    latitude: 14.6397,
    longitude: 121.0779,
    image_url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-03",
    name: "UP Anvil Tech iHub",
    type: "Regional iHub",
    institution: "University of the Philippines Diliman",
    province: "Quezon City",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "National Engineering Center, UP Diliman, Quezon City",
    focal_person: "Prof. Luis Sison",
    contact_number: "0918-222-3333",
    email: "luis.sison@up.edu.ph",
    latitude: 14.6548,
    longitude: 121.0700,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  // Provincial/Municipal style hubs in NCR (7 items)
  {
    id: "ihub-ncr-04",
    name: "Manila Makers Hub",
    type: "Provincial iHub",
    institution: "TUP Manila Campus",
    province: "Manila",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "Ayala Blvd, Ermita, Manila",
    focal_person: "Engr. Ronald R. Medina",
    contact_number: "0917-444-5555",
    email: "r.medina@tup.edu.ph",
    latitude: 14.5888,
    longitude: 120.9850,
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-05",
    name: "Makati Tech Synergy",
    type: "Provincial iHub",
    institution: "University of Makati",
    province: "Makati",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "J.P. Rizal Ext, Makati City",
    focal_person: "Dr. Elyxzur C. Ramos",
    contact_number: "0920-555-6666",
    email: "elyxzur.ramos@umak.edu.ph",
    latitude: 14.5615,
    longitude: 121.0583,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-06",
    name: "Taguig Innovation Station",
    type: "Provincial iHub",
    institution: "Taguig City University",
    province: "Taguig",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "Gen. Santos Ave, Central Bicutan, Taguig",
    focal_person: "Rosario E. Diaz",
    contact_number: "0919-666-7777",
    email: "r.diaz@tcu.edu.ph",
    latitude: 14.4891,
    longitude: 121.0494,
    image_url: "https://images.unsplash.com/photo-1558403194-611308249627?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-07",
    name: "Pasig Smart City Hub",
    type: "Provincial iHub",
    institution: "PLSP Pasig",
    province: "Pasig",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "Alcalde Jose Way, Kapasigan, Pasig City",
    focal_person: "Atty. Glicerio G. Sicat",
    contact_number: "0939-777-8888",
    email: "g.sicat@plsp.edu.ph",
    latitude: 14.5614,
    longitude: 121.0827,
    image_url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-08",
    name: "San Juan Digital Center",
    type: "Provincial iHub",
    institution: "San Juan City Hall Compound",
    province: "San Juan",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "N. Domingo St., San Juan",
    focal_person: "Francis N. Zamora",
    contact_number: "0917-888-9999",
    email: "mayor@sanjuan.gov.ph",
    latitude: 14.6047,
    longitude: 121.0305,
    image_url: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-09",
    name: "Mandaluyong Tech Space",
    type: "Provincial iHub",
    institution: "RTU Mandaluyong",
    province: "Mandaluyong City",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "Boni Ave, Mandaluyong City",
    focal_person: "Dr. Ma. Andrea L. Flores",
    contact_number: "0920-111-3333",
    email: "ma.flores@rtu.edu.ph",
    latitude: 14.5772,
    longitude: 121.0321,
    image_url: "https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-ncr-10",
    name: "Caloocan Industry Hub",
    type: "Provincial iHub",
    institution: "University of Caloocan City",
    province: "Caloocan",
    province_iso: "PH-MNL",
    region_iso: "PH-00",
    address: "Biglang Awa St, Grace Park East, Caloocan",
    focal_person: "Dr. Marilyn De Jesus",
    contact_number: "0998-333-2222",
    email: "dejesus.marilyn@ucc.edu.ph",
    latitude: 14.6592,
    longitude: 120.9922,
    image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // --- REGION 3: CENTRAL LUZON (8 iHubs: 2 Regional, 6 Provincial) ---
  {
    id: "ihub-r3-01",
    name: "CLSU Agriculture Hub",
    type: "Regional iHub",
    institution: "Central Luzon State University",
    province: "Nueva Ecija",
    province_iso: "PH-NUE",
    region_iso: "PH-03",
    address: "CLSU Campus, Science City of Muñoz, Nueva Ecija",
    focal_person: "Dr. Edgar A. Orden",
    contact_number: "0917-333-7777",
    email: "e.orden@clsu.edu.ph",
    latitude: 15.7414,
    longitude: 120.9388,
    image_url: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r3-02",
    name: "Pampanga Tech Incubator",
    type: "Regional iHub",
    institution: "Don Honorio Ventura State University",
    province: "Pampanga",
    province_iso: "PH-PAM",
    region_iso: "PH-03",
    address: "DHVSU Main Campus, Bacolor, Pampanga",
    focal_person: "Dr. Enrique G. Baking",
    contact_number: "0920-444-8888",
    email: "eg.baking@dhvsu.edu.ph",
    latitude: 15.0002,
    longitude: 120.6558,
    image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r3-03",
    name: "Bulacan Innovation Center",
    type: "Provincial iHub",
    institution: "Bulacan State University",
    province: "Bulacan",
    province_iso: "PH-BUL",
    region_iso: "PH-03",
    address: "BulSU Campus, Guinhawa, Malolos City, Bulacan",
    focal_person: "Dr. Cecilia N. Gascon",
    contact_number: "0919-555-9999",
    email: "c.gascon@bulsu.edu.ph",
    latitude: 14.8583,
    longitude: 120.8144,
    image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r3-04",
    name: "Bataan Peninsula Hub",
    type: "Provincial iHub",
    institution: "Bataan Peninsula State University",
    province: "Bataan",
    province_iso: "PH-BAN",
    region_iso: "PH-03",
    address: "BPSU Campus, Capitol Compound, Balanga City, Bataan",
    focal_person: "Dr. Gregorio J. Rodis",
    contact_number: "0998-111-2222",
    email: "g.rodis@bpsu.edu.ph",
    latitude: 14.6791,
    longitude: 120.5406,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r3-05",
    name: "Zambales Coastal iHub",
    type: "Provincial iHub",
    institution: "Ramon Magsaysay State University",
    province: "Zambales",
    province_iso: "PH-ZMB",
    region_iso: "PH-03",
    address: "RMSU Main Campus, Iba, Zambales",
    focal_person: "Dr. Roy N. Villalobos",
    contact_number: "0917-222-4444",
    email: "r.villalobos@rmsu.edu.ph",
    latitude: 15.3283,
    longitude: 119.9822,
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r3-06",
    name: "Tarlac Technological Center",
    type: "Provincial iHub",
    institution: "Tarlac State University",
    province: "Tarlac",
    province_iso: "PH-TAR",
    region_iso: "PH-03",
    address: "TSU Villa Lucinda Campus, Tarlac City",
    focal_person: "Dr. Arnold E. Velasco",
    contact_number: "0920-888-7777",
    email: "a.velasco@tsu.edu.ph",
    latitude: 15.4578,
    longitude: 120.5901,
    image_url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r3-07",
    name: "Aurora Agri-Tech Hub",
    type: "Provincial iHub",
    institution: "Aurora State College of Tech",
    province: "Aurora",
    province_iso: "PH-AUR",
    region_iso: "PH-03",
    address: "ASCOT Zabali Campus, Baler, Aurora",
    focal_person: "Dr. Eutiquio L. Rotaquio Jr.",
    contact_number: "0919-999-0000",
    email: "e.rotaquio@ascot.edu.ph",
    latitude: 15.7533,
    longitude: 121.5714,
    image_url: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r3-08",
    name: "Olongapo Makers Hub",
    type: "Provincial iHub",
    institution: "Olongapo City College",
    province: "Olongapo",
    province_iso: "PH-ZMB",
    region_iso: "PH-03",
    address: "Rizal Ave, Olongapo City",
    focal_person: "Engr. Nestor T. Almendral",
    contact_number: "0917-777-5555",
    email: "n.almendral@occ.edu.ph",
    latitude: 14.8272,
    longitude: 120.2811,
    image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // --- REGION 4-A: CALABARZON (9 iHubs: 2 Regional, 7 Provincial) ---
  {
    id: "ihub-r4a-01",
    name: "Cavite Innovation Lab",
    type: "Regional iHub",
    institution: "Cavite State University",
    province: "Cavite",
    province_iso: "PH-CAV",
    region_iso: "PH-40",
    address: "CvSU Main Campus, Indang, Cavite",
    focal_person: "Dr. Hernando D. Robles",
    contact_number: "0917-555-4444",
    email: "h.robles@cvsu.edu.ph",
    latitude: 14.1983,
    longitude: 120.8809,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-02",
    name: "Laguna Science Park iHub",
    type: "Regional iHub",
    institution: "UPLB Technology Incubator",
    province: "Laguna",
    province_iso: "PH-LAG",
    region_iso: "PH-40",
    address: "UPLB Campus, Los Baños, Laguna",
    focal_person: "Dr. Jose V. Camacho Jr.",
    contact_number: "0920-666-5555",
    email: "chancellor@uplb.edu.ph",
    latitude: 14.1675,
    longitude: 121.2442,
    image_url: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-03",
    name: "Batangas Provincial iHub",
    type: "Provincial iHub",
    institution: "Batangas State University",
    province: "Batangas",
    province_iso: "PH-BTG",
    region_iso: "PH-40",
    address: "BatStateU Alangilan Campus, Golden Country Subd., Batangas City",
    focal_person: "Dr. Tirso A. Ronquillo",
    contact_number: "0917-888-2233",
    email: "pres.ronquillo@g.batstate-u.edu.ph",
    latitude: 13.7744,
    longitude: 121.0772,
    image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-04",
    name: "Rizal Tech Incubator",
    type: "Provincial iHub",
    institution: "University of Rizal System",
    province: "Rizal",
    province_iso: "PH-RIZ",
    region_iso: "PH-40",
    address: "URS Morong Campus, Morong, Rizal",
    focal_person: "Dr. Nancy T. Pascual",
    contact_number: "0920-333-2211",
    email: "pres.office@urs.edu.ph",
    latitude: 14.5203,
    longitude: 121.2369,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-05",
    name: "Quezon Coco-Tech Hub",
    type: "Provincial iHub",
    institution: "Southern Luzon State University",
    province: "Quezon",
    province_iso: "PH-QUE",
    region_iso: "PH-40",
    address: "SLSU Main Campus, Lucban, Quezon",
    focal_person: "Dr. Doracie B. Zoleta-Nantes",
    contact_number: "0919-444-1100",
    email: "pres.nantes@slsu.edu.ph",
    latitude: 14.1169,
    longitude: 121.5542,
    image_url: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-06",
    name: "Lucena Provincial Hub",
    type: "Provincial iHub",
    institution: "DOST Quezon PSTO Office",
    province: "Quezon",
    province_iso: "PH-QUE",
    region_iso: "PH-40",
    address: "Diversion Road, Brgy. Domoit, Lucena City",
    focal_person: "Engr. Maria Esperanza E. Jawili",
    contact_number: "0917-333-9988",
    email: "me.jawili@ro4a.dost.gov.ph",
    latitude: 13.9614,
    longitude: 121.5892,
    image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-07",
    name: "Dasmarinas Smart Space",
    type: "Provincial iHub",
    institution: "DLSU Dasmariñas",
    province: "Cavite",
    province_iso: "PH-CAV",
    region_iso: "PH-40",
    address: "DBB-B, Dasmariñas City, Cavite",
    focal_person: "Dr. Francisco M. De Rosa",
    contact_number: "0998-555-1122",
    email: "fderosa@dlsud.edu.ph",
    latitude: 14.3283,
    longitude: 120.9575,
    image_url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-08",
    name: "Calamba ICT Hub",
    type: "Provincial iHub",
    institution: "City College of Calamba",
    province: "Laguna",
    province_iso: "PH-LAG",
    region_iso: "PH-40",
    address: "Chipeco Ave, Calamba, Laguna",
    focal_person: "Dr. Ronald A. Gonzales",
    contact_number: "0920-777-6655",
    email: "pres.gonzales@ccc.edu.ph",
    latitude: 14.2072,
    longitude: 121.1578,
    image_url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4a-09",
    name: "Antipolo Innovation Station",
    type: "Provincial iHub",
    institution: "Antipolo Institute of Technology",
    province: "Rizal",
    province_iso: "PH-RIZ",
    region_iso: "PH-40",
    address: "Marigman Rd, Brgy. San Roque, Antipolo, Rizal",
    focal_person: "Dr. Corazon S. Mateo",
    contact_number: "0917-888-7711",
    email: "c.mateo@urs.edu.ph",
    latitude: 14.5828,
    longitude: 121.1667,
    image_url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // --- REGION 7: CENTRAL VISAYAS (8 iHubs: 2 Regional, 6 Provincial) ---
  {
    id: "ihub-r7-01",
    name: "Cebu Tech Incubator",
    type: "Regional iHub",
    institution: "Cebu Technological University",
    province: "Cebu",
    province_iso: "PH-CEB",
    region_iso: "PH-07",
    address: "CTU Main Campus, M.J. Cuenco Ave, Cebu City",
    focal_person: "Dr. Rosein A. Ancheta Jr.",
    contact_number: "0917-666-8888",
    email: "pres.ancheta@ctu.edu.ph",
    latitude: 10.2970,
    longitude: 123.9069,
    image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r7-02",
    name: "Bohol Innovation Lab",
    type: "Regional iHub",
    institution: "Bohol Island State University",
    province: "Bohol",
    province_iso: "PH-BOH",
    region_iso: "PH-07",
    address: "BISU Main Campus, Tagbilaran City, Bohol",
    focal_person: "Dr. Regucivilla A. Pobar",
    contact_number: "0920-555-4433",
    email: "rpobar@bisu.edu.ph",
    latitude: 9.6496,
    longitude: 123.8569,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r7-03",
    name: "Negros Oriental iHub",
    type: "Provincial iHub",
    institution: "Negros Oriental State University",
    province: "Negros Oriental",
    province_iso: "PH-NER",
    region_iso: "PH-07",
    address: "NORSU Main Campus, Kagawasan Ave, Dumaguete City",
    focal_person: "Dr. Joel P. Limson",
    contact_number: "0919-222-8888",
    email: "president@norsu.edu.ph",
    latitude: 9.3175,
    longitude: 123.3039,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r7-04",
    name: "Siquijor Mystic iHub",
    type: "Provincial iHub",
    institution: "Siquijor State College",
    province: "Siquijor",
    province_iso: "PH-SIG",
    region_iso: "PH-07",
    address: "SSC Campus, Larena, Siquijor",
    focal_person: "Dr. Lope S. Buenance",
    contact_number: "0998-123-9988",
    email: "pres.buenance@ssc.edu.ph",
    latitude: 9.2483,
    longitude: 123.5939,
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r7-05",
    name: "Mandaue Makers Space",
    type: "Provincial iHub",
    institution: "Mandaue City College",
    province: "Cebu",
    province_iso: "PH-CEB",
    region_iso: "PH-07",
    address: "Don Andres Soriano Ave, Mandaue City, Cebu",
    focal_person: "Dr. Lily D. Lim",
    contact_number: "0917-444-1122",
    email: "lily.lim@mcc.edu.ph",
    latitude: 10.3294,
    longitude: 123.9436,
    image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r7-06",
    name: "Lapu-Lapu Cyber Hub",
    type: "Provincial iHub",
    institution: "Lapu-Lapu City College",
    province: "Cebu",
    province_iso: "PH-CEB",
    region_iso: "PH-07",
    address: "Don B. Benedicto Rd, Gun-ob, Lapu-Lapu City, Cebu",
    focal_person: "Dr. Eduardo A. Ompad",
    contact_number: "0920-888-2233",
    email: "eduardo.ompad@llcc.edu.ph",
    latitude: 10.3150,
    longitude: 123.9500,
    image_url: "https://images.unsplash.com/photo-1558403194-611308249627?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r7-07",
    name: "Tagbilaran Smart Station",
    type: "Provincial iHub",
    institution: "DOST Bohol PSTO Office",
    province: "Bohol",
    province_iso: "PH-BOH",
    region_iso: "PH-07",
    address: "Bintana St, Tagbilaran City",
    focal_person: "Vina R. Antopina",
    contact_number: "0917-345-0987",
    email: "v.antopina@region7.dost.gov.ph",
    latitude: 9.6450,
    longitude: 123.8610,
    image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r7-08",
    name: "Talibon Innovation Hub",
    type: "Provincial iHub",
    institution: "BISU Talibon Campus",
    province: "Bohol",
    province_iso: "PH-BOH",
    region_iso: "PH-07",
    address: "BISU, Talibon, Bohol",
    focal_person: "Dr. Maria Fe C. Alidon",
    contact_number: "0919-654-1122",
    email: "pres.alidon@bisu.edu.ph",
    latitude: 10.1472,
    longitude: 124.3297,
    image_url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // --- REGION 11: DAVAO REGION (8 iHubs: 2 Regional, 6 Provincial) ---
  {
    id: "ihub-r11-01",
    name: "Davao Tech Incubator",
    type: "Regional iHub",
    institution: "University of Southeastern Philippines",
    province: "Davao del Sur",
    province_iso: "PH-DAS",
    region_iso: "PH-11",
    address: "USeP Obrero Campus, Iñigo St, Bajada, Davao City",
    focal_person: "Dr. Lourdes C. Generalao",
    contact_number: "0917-888-0000",
    email: "president@usep.edu.ph",
    latitude: 7.0869,
    longitude: 125.6144,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r11-02",
    name: "UP Mindanao Tech Hub",
    type: "Regional iHub",
    institution: "University of the Philippines Mindanao",
    province: "Davao del Sur",
    province_iso: "PH-DAS",
    region_iso: "PH-11",
    address: "UP Mindanao, Tugbok, Mintal, Davao City",
    focal_person: "Prof. Lyre Anni E. Murao",
    contact_number: "0920-555-1111",
    email: "chancellor@upmin.edu.ph",
    latitude: 7.0700,
    longitude: 125.4858,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r11-03",
    name: "Davao del Norte Provincial Hub",
    type: "Provincial iHub",
    institution: "Davao del Norte State College",
    province: "Davao del Norte",
    province_iso: "PH-DAV",
    region_iso: "PH-11",
    address: "DNSC Campus, New Visayas, Panabo City, Davao del Norte",
    focal_person: "Dr. Joy M. Sorrosa",
    contact_number: "0919-444-2222",
    email: "joy.sorrosa@dnsc.edu.ph",
    latitude: 7.3061,
    longitude: 125.6888,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r11-04",
    name: "Davao de Oro Innovation Hub",
    type: "Provincial iHub",
    institution: "Compostela Valley State College",
    province: "Compostela Valley",
    province_iso: "PH-COM",
    region_iso: "PH-11",
    address: "CVSC Main Campus, Nabunturan, Davao de Oro",
    focal_person: "Dr. Christie Jean V. Ganiera",
    contact_number: "0998-333-4444",
    email: "president@cvsc.edu.ph",
    latitude: 7.6067,
    longitude: 125.9669,
    image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r11-05",
    name: "Davao Oriental Innovation Lab",
    type: "Provincial iHub",
    institution: "Davao Oriental State University",
    province: "Davao Oriental",
    province_iso: "PH-DAO",
    region_iso: "PH-11",
    address: "DORSU Campus, Dahican, Mati City, Davao Oriental",
    focal_person: "Dr. Roy G. Ponce",
    contact_number: "0917-111-9999",
    email: "president@dorsu.edu.ph",
    latitude: 6.9450,
    longitude: 126.2169,
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r11-06",
    name: "Davao del Sur Provincial Hub",
    type: "Provincial iHub",
    institution: "DOST Davao del Sur PSTO",
    province: "Davao del Sur",
    province_iso: "PH-DAS",
    region_iso: "PH-11",
    address: "Lim Extension, Digos City, Davao del Sur",
    focal_person: "Engr. Maria Ester M. Lindo",
    contact_number: "0917-777-6666",
    email: "m.lindo@region11.dost.gov.ph",
    latitude: 6.7533,
    longitude: 125.3567,
    image_url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r11-07",
    name: "Tagum Smart City Hub",
    type: "Provincial iHub",
    institution: "USEP Tagum Campus",
    province: "Davao del Norte",
    province_iso: "PH-DAV",
    region_iso: "PH-11",
    address: "USEP Tagum, Apokon, Tagum City",
    focal_person: "Dr. Cesar A. Limbaga Jr.",
    contact_number: "0920-555-8899",
    email: "pres.limbaga@usep.edu.ph",
    latitude: 7.4472,
    longitude: 125.8211,
    image_url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r11-08",
    name: "Mati Coastal Incubator",
    type: "Provincial iHub",
    institution: "DOST Davao Oriental PSTO Office",
    province: "Davao Oriental",
    province_iso: "PH-DAO",
    region_iso: "PH-11",
    address: "Government Center, Capitol Hills, Mati City",
    focal_person: "Vapor G. Linsag",
    contact_number: "0919-333-2211",
    email: "v.linsag@region11.dost.gov.ph",
    latitude: 6.9530,
    longitude: 126.2210,
    image_url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // --- EXTRA DISTRIBUTED HUBS (22 iHubs scattered across other regions to reach 78) ---
  // Region 1: Ilocos (4 iHubs)
  {
    id: "ihub-r1-01",
    name: "Ilocos Innovation Lab",
    type: "Regional iHub",
    institution: "Don Mariano Marcos Memorial State University",
    province: "La Union",
    province_iso: "PH-LUN",
    region_iso: "PH-01",
    address: "DMMMSU Campus, Bacnotan, La Union",
    focal_person: "Dr. Jaime I. Manuel Jr.",
    contact_number: "0917-888-1111",
    email: "president@dmmmsu.edu.ph",
    latitude: 16.7169,
    longitude: 120.3542,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r1-02",
    name: "Pangasinan Tech Space",
    type: "Provincial iHub",
    institution: "Pangasinan State University",
    province: "Pangasinan",
    province_iso: "PH-PAN",
    region_iso: "PH-01",
    address: "PSU Lingayen Campus, Alvear St, Lingayen, Pangasinan",
    focal_person: "Dr. Elbert M. Galas",
    contact_number: "0920-555-2222",
    email: "egalas@psu.edu.ph",
    latitude: 16.0206,
    longitude: 120.2319,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r1-03",
    name: "Ilocos Sur Crafts iHub",
    type: "Provincial iHub",
    institution: "University of Northern Philippines",
    province: "Ilocos Sur",
    province_iso: "PH-ILS",
    region_iso: "PH-01",
    address: "UNP Campus, Tamag, Vigan City, Ilocos Sur",
    focal_person: "Dr. Erwin F. Cadorna",
    contact_number: "0919-444-3333",
    email: "president@unp.edu.ph",
    latitude: 17.5700,
    longitude: 120.3778,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r1-04",
    name: "Ilocos Norte Tech Hub",
    type: "Provincial iHub",
    institution: "Mariano Marcos State University",
    province: "Ilocos Norte",
    province_iso: "PH-ILN",
    region_iso: "PH-01",
    address: "MMSU Campus, Batac City, Ilocos Norte",
    focal_person: "Dr. Shirley C. Agrupis",
    contact_number: "0998-111-4444",
    email: "shirley.agrupis@mmsu.edu.ph",
    latitude: 18.0617,
    longitude: 120.5408,
    image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // Region 2: Cagayan Valley (3 iHubs)
  {
    id: "ihub-r2-01",
    name: "Cagayan Valley Innovation Lab",
    type: "Regional iHub",
    institution: "Cagayan State University",
    province: "Cagayan",
    province_iso: "PH-CAG",
    region_iso: "PH-02",
    address: "CSU Carig Campus, Tuguegarao City, Cagayan",
    focal_person: "Dr. Urdujah G. Alvarado",
    contact_number: "0917-888-5555",
    email: "alvarado.urdujah@csu.edu.ph",
    latitude: 17.6367,
    longitude: 121.7588,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r2-02",
    name: "Isabela Innovation Space",
    type: "Provincial iHub",
    institution: "Isabela State University",
    province: "Isabela",
    province_iso: "PH-ISA",
    region_iso: "PH-02",
    address: "ISU Echague Campus, Echague, Isabela",
    focal_person: "Dr. Ricmar P. Aquino",
    contact_number: "0920-555-6666",
    email: "president@isu.edu.ph",
    latitude: 16.7161,
    longitude: 121.6703,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r2-03",
    name: "Quirino Provincial iHub",
    type: "Provincial iHub",
    institution: "Quirino State University",
    province: "Quirino",
    province_iso: "PH-QUI",
    region_iso: "PH-02",
    address: "QSU Diffun Campus, Diffun, Quirino",
    focal_person: "Dr. Hermenegildo F. Dumlao",
    contact_number: "0919-444-7777",
    email: "president@qsu.edu.ph",
    latitude: 16.6214,
    longitude: 121.5422,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // Region 4-B: MIMAROPA (3 iHubs)
  {
    id: "ihub-r4b-01",
    name: "MIMAROPA Food Hub",
    type: "Regional iHub",
    institution: "Mindoro State University",
    province: "Oriental Mindoro",
    province_iso: "PH-MDR",
    region_iso: "PH-41",
    address: "MinSU Victoria Campus, Victoria, Oriental Mindoro",
    focal_person: "Dr. Levy B. Arago Jr.",
    contact_number: "0917-888-6666",
    email: "president@minsu.edu.ph",
    latitude: 13.1611,
    longitude: 121.2803,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4b-02",
    name: "Palawan Eco-Innovation Hub",
    type: "Provincial iHub",
    institution: "Palawan State University",
    province: "Palawan",
    province_iso: "PH-PLW",
    region_iso: "PH-41",
    address: "PSU Campus, Tiniguiban, Puerto Princesa City, Palawan",
    focal_person: "Dr. Ramon M. Docto",
    contact_number: "0920-555-7777",
    email: "rdocto@psu.palawan.edu.ph",
    latitude: 9.7788,
    longitude: 118.7350,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r4b-03",
    name: "Romblon Marble iHub",
    type: "Provincial iHub",
    institution: "Romblon State University",
    province: "Romblon",
    province_iso: "PH-ROM",
    region_iso: "PH-41",
    address: "RSU Main Campus, Odiongan, Romblon",
    focal_person: "Dr. Merian P. Catajay-Mani",
    contact_number: "0919-444-8888",
    email: "president@rsu.edu.ph",
    latitude: 12.3986,
    longitude: 121.9806,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // Region 5: Bicol (3 iHubs)
  {
    id: "ihub-r5-01",
    name: "Bicol Tech Incubator",
    type: "Regional iHub",
    institution: "Bicol University",
    province: "Albay",
    province_iso: "PH-ALB",
    region_iso: "PH-05",
    address: "BU East Campus, Legazpi City, Albay",
    focal_person: "Dr. Baby Boy Benjamin D. Nebres III",
    contact_number: "0917-888-7777",
    email: "bbdnebres@bicol-u.edu.ph",
    latitude: 13.1367,
    longitude: 123.7208,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r5-02",
    name: "Camarines Sur Agri-iHub",
    type: "Provincial iHub",
    institution: "Central Bicol State University of Agri",
    province: "Camarines Sur",
    province_iso: "PH-CAS",
    region_iso: "PH-05",
    address: "CBSUA Campus, Pili, Camarines Sur",
    focal_person: "Dr. Alberto N. Naperi",
    contact_number: "0920-555-8888",
    email: "president@cbsua.edu.ph",
    latitude: 13.5833,
    longitude: 123.2833,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r5-03",
    name: "Sorsogon Provincial Hub",
    type: "Provincial iHub",
    institution: "Sorsogon State University",
    province: "Sorsogon",
    province_iso: "PH-SOR",
    region_iso: "PH-05",
    address: "SSU Campus, Sorsogon City, Sorsogon",
    focal_person: "Dr. Geraldine F. De Jesus",
    contact_number: "0919-444-9999",
    email: "president@sorsu.edu.ph",
    latitude: 12.9667,
    longitude: 124.0000,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // Region 8: Eastern Visayas (3 iHubs)
  {
    id: "ihub-r8-01",
    name: "EV Innovation Center",
    type: "Regional iHub",
    institution: "Eastern Visayas State University",
    province: "Leyte",
    province_iso: "PH-LEY",
    region_iso: "PH-08",
    address: "EVSU Campus, Salazar St, Tacloban City, Leyte",
    focal_person: "Dr. Dennis C. de Paz",
    contact_number: "0917-888-8888",
    email: "president@evsu.edu.ph",
    latitude: 11.2417,
    longitude: 125.0044,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r8-02",
    name: "Samar Tech Space",
    type: "Provincial iHub",
    institution: "Samar State University",
    province: "Samar",
    province_iso: "PH-WSA",
    region_iso: "PH-08",
    address: "SSU Campus, Catbalogan City, Samar",
    focal_person: "Dr. Marilyn D. Cardoso",
    contact_number: "0920-555-9999",
    email: "president@ssu.edu.ph",
    latitude: 11.7833,
    longitude: 124.8833,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r8-03",
    name: "Southern Leyte Agri-Hub",
    type: "Provincial iHub",
    institution: "Southern Leyte State University",
    province: "Southern Leyte",
    province_iso: "PH-SLE",
    region_iso: "PH-08",
    address: "SLSU Campus, Sogod, Southern Leyte",
    focal_person: "Dr. Jude A. Duarte",
    contact_number: "0919-444-0000",
    email: "jduarte@slsu.edu.ph",
    latitude: 10.3833,
    longitude: 124.9833,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // Region 10: Northern Mindanao (3 iHubs)
  {
    id: "ihub-r10-01",
    name: "USTP Innovation Hub",
    type: "Regional iHub",
    institution: "University of Science and Tech of Southern PH",
    province: "Misamis Oriental",
    province_iso: "PH-MSR",
    region_iso: "PH-10",
    address: "USTP Campus, C.M. Recto Ave, Cagayan de Oro City",
    focal_person: "Dr. Ambrosio B. Cultura II",
    contact_number: "0917-888-9999",
    email: "president@ustp.edu.ph",
    latitude: 8.4858,
    longitude: 124.6567,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r10-02",
    name: "Lanao del Norte Tech Space",
    type: "Provincial iHub",
    institution: "MSU - Iligan Institute of Technology",
    province: "Lanao del Norte",
    province_iso: "PH-LAN",
    region_iso: "PH-10",
    address: "MSU-IIT Campus, Andres Bonifacio Ave, Iligan City",
    focal_person: "Dr. Alizedney M. Ditucalan",
    contact_number: "0920-555-0000",
    email: "president@g.msuiit.edu.ph",
    latitude: 8.2281,
    longitude: 124.2442,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-r10-03",
    name: "Bukidnon Agro-Tech Hub",
    type: "Provincial iHub",
    institution: "Bukidnon State University",
    province: "Bukidnon",
    province_iso: "PH-BUK",
    region_iso: "PH-10",
    address: "BukSU Campus, Fortich St, Malaybalay City, Bukidnon",
    focal_person: "Dr. Joy M. Mirasol",
    contact_number: "0919-444-1111",
    email: "president@buksu.edu.ph",
    latitude: 8.1578,
    longitude: 125.1264,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },

  // CAR: Cordillera Administrative Region (3 iHubs)
  {
    id: "ihub-car-01",
    name: "Cordillera Highlands iHub",
    type: "Regional iHub",
    institution: "Benguet State University",
    province: "Benguet",
    province_iso: "PH-BEN",
    region_iso: "PH-15",
    address: "BSU Campus, La Trinidad, Benguet",
    focal_person: "Dr. Felipe S. Comila",
    contact_number: "0917-888-2222",
    email: "president@bsu.edu.ph",
    latitude: 16.4533,
    longitude: 120.5900,
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-car-02",
    name: "Abra Traditional Crafts Hub",
    type: "Provincial iHub",
    institution: "Abra State Institute of Sciences & Tech",
    province: "Abra",
    province_iso: "PH-ABR",
    region_iso: "PH-15",
    address: "ASIST Campus, Bangued, Abra",
    focal_person: "Dr. Gregorio T. Turqueza Jr.",
    contact_number: "0920-555-3333",
    email: "president@asist.edu.ph",
    latitude: 17.5978,
    longitude: 120.6203,
    image_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  },
  {
    id: "ihub-car-03",
    name: "Kalinga Heritage iHub",
    type: "Provincial iHub",
    institution: "Kalinga State University",
    province: "Kalinga",
    province_iso: "PH-KAL",
    region_iso: "PH-15",
    address: "KSU Campus, Tabuk City, Kalinga",
    focal_person: "Dr. Eduardo T. Bagtang",
    contact_number: "0919-444-2222",
    email: "president@ksu.edu.ph",
    latitude: 17.4167,
    longitude: 121.4333,
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80",
    status: "Active"
  }
];

// Combine into window namespace for direct loading in the browser
window.iHubDatabase = {
  regions: mockRegions,
  ihubs: mockIHubs
};
